### ISSUE TITLE
Вероятная ошибка в ссылках на архивы

### ISSUE THREAD

**Issue by vladimir-doroshenko** [imaginal/nabuvote#1]
https://github.com/imaginal/nabuvote/blob/master/system/candidates.php#L43
В конфигурации кандидатов, начиная с id=40, ссылки на архивы не соответствуют id кандидата

**Comment by imaginal** [comment]
it's ok that the "id" and "link" to the rar are not the same (http://nabu.gov.ua/index.php?id=14)
