### ISSUE TITLE
Something modern?

### ISSUE THREAD

**Issue by a-b** [imaginal/nabuvote#10]
http://www.codeigniter.com/

**Comment by frol** [comment]
It will make code overcomplicated. The project works and works fine without a framework.

**Comment by imaginal** [comment]
Tnx for advice. Of course I do! In future. But now imagine that you have a strong limit of lines of code, about two thousand including templates, how big codeigniter? Can I examine it in three days, in a week? It was imperative for this system. But it does not affect any other systems.
