### ISSUE TITLE
В требованиях указать используемый вебсервер

### ISSUE THREAD

**Issue by elcreator** [imaginal/nabuvote#14]
В коде есть htaccess, но в требованиях нет apache.
Нужно или добавить варианты конфига для nginx, или четко прописать, что нужен именно apache.

**Comment by imaginal** [comment]
htacess это не руководство к действию, а скорее намек, какую папку открыть, какую закрыть. Веб сервер не может быть требованием к веб-приложению исполняемому отдельным интерпритатором, каждый в праве выбрать то, что ему удобнее, Apache, nginx, lighttpd, IIS или что-то еще. Хотя в качестве таких же примеров, конфиги для веб серверов возможно появятся но позже.
