### ISSUE TITLE
Подпись результатов с помощью openssl_private_encrypt

### ISSUE THREAD

**Issue by dev-rkoshlyak** [imaginal/nabuvote#15]
https://nabu-test.ed.org.ua/public/report.txt - возвращает результаты какие то во время голосование.
Потом я скажу что мне показывались результаты другие во время голосование, и сделаю скрин какой то. И буду говорить что вы врете.
Что бы этого не случилось, подпишите результаты приватным ключем, и опубликуйте публичный ключ, что бы можна было проверить результаты.

Процедура следующая (по коду это где то 100 строчек, смотрите пример):
1) Генерируете private/public ключи.
2) Публикуете public ключ.
3) Все результаты персональные и report.txt подписываете, private ключем.
4) Каждый человек может проверить это с помощью публичного ключа.
5) В конце голосование удаляете private ключ.
Если кто нибуть показывает вам результаты голосование которые не соответсвуют опубликованым вами в конце и можна проверить public key. 
То это значит что ваша система не работает, кто то хакнул сервер или сисадмин подхимичил что то, или кто то украл private key, что тоже самое что кто то вас хакнул и результаты не действительные. 

http://www.programering.com/a/MDO2cDMwATQ.html - это достаточно просто, порядка 100 строчек

**Comment by imaginal** [comment]
Не так страшна подмена наблюдателем, как подмена организатором выборов, а такое решение от этого к сожалению не защищает. В принципе обсуждаемо для других голосований. Сейчас наверное не реализуемо, для этого есть юридические преграды.
