### ISSUE TITLE
Сделайте результаты голосование скрытыми до конца голосования

### ISSUE THREAD

**Issue by dev-rkoshlyak** [imaginal/nabuvote#16]
#15 - то же самое что и тут, только наоборот.

Новая пара private/public key.
результаты персонального голосование шифруете публичным ключем + random строчка вконце.
В конце голосование публикуете private key, ну и розшифровываете все результаты.

Это гарантирует что результаты голосование нельзя манипулировать и они будут тайными до конца голосования.

Ну тут сложнее так как нам прийдеться доверять сисадмину что он приватный ключ никому не покажет до конца голосования.

**Comment by imaginal** [comment]
В конкретном конкурсе в общественный совет уже утверждены условия и протокол должен быть публичным, что касается других голосований — это вполне обсуждаемо.
