### ISSUE TITLE
Use filter_var function to validate/fiter input data (emails etc.) instead regexp

### ISSUE THREAD

**Issue by vladimir-doroshenko** [imaginal/nabuvote#2]
https://github.com/imaginal/nabuvote/blob/master/step2.php#L26

**Comment by imaginal** [comment]
какие +/- у filter_var по сравнению с preg_match? в конкретном случае мне важнее предотвратить иньекцию в заголовки письма, чем отловить ошибочный адрес, на который просто не дойдет письмо.

**Comment by vladimir-doroshenko** [comment]
Самый жирный плюс - это минус три if'a https://github.com/imaginal/nabuvote/blob/master/step2.php#L48

**Comment by imaginal** [comment]
Я не знаю страхует ли filter_var от иньекций в заголовки письма и из документации этого не следует. Поэтому пока (до подробных тестов) оставлю явную проверку на перевод строки.

**Comment by vladimir-doroshenko** [comment]
\n и , точно фильтрует, ' схавал. В общем, можно закрывать. Лучше перебдеть ;)
