### ISSUE TITLE
Проверка правильности e-mail'а делается два раза

### ISSUE THREAD

**Issue by frol** [imaginal/nabuvote#3]
https://github.com/imaginal/nabuvote/blob/master/step2.php#L47
https://github.com/imaginal/nabuvote/blob/master/system/functions.php#L291

К тому же, как-то мало условий валидаций, но я пока не нашёл конкретного контр-примера. ([php реализация mail](https://github.com/php/php-src/blob/master/ext/standard/mail.c#L103))

**Comment by imaginal** [comment]
Ну это немного разные проверки, одна на простейший regex вторая на иньекции в заголовки и тут лучше перепроверить ;)
