### ISSUE TITLE
Уникальность email под вопросом

### ISSUE THREAD

**Issue by frol** [imaginal/nabuvote#5]
Возможно, имеет смысл сохранять в БД и проверять на уникальность email'ы без учёта фич с "+" и множественным использованием точек?

vasya.pupkin@gmail.com == vasyapupkin+100500@gmail.com == ...

**Comment by dchaplinsky** [comment]
+1

**Comment by imaginal** [comment]
+/- про эту фичу GMail знают единицы, это редкая фича и закладываться из-за них на отдельную проверку и увеличивать код я бы не стал, в базе на идексе стоит UNIQUE и это главная защита, остальных можно потом выкосить из публичного протокола.

**Comment by frol** [comment]
@imaginal не так уж сложно сделать, строчки три кода добавит, но моё дело ткнуть пальцем, а код твой.

**Comment by crimaniak** [comment]
Кому надо про подобные фичи знают, можете не сомневаться.

**Comment by dchaplinsky** [comment]
Я не думаю, что стоит что–то выкашивать из публичного протокола, кстати

**Comment by frol** [comment]
Кстати да, для выкашивания из публичного протокола лишняя работа нужна будет, да ещё и как-то публично это проводить, иначе смысла с такого голосования мало (ИМХО). Куда проще три строчки сразу дописать.

**Comment by imaginal** [comment]
Убрал '+' из регекспа, начали использовать фичу с '.' — это именно то о чем я говорил, не имеет смысла закрываться от особенностей отдельной почтовой системы, пусть даже популярной. Ограждаться нужно в другом месте. А всех манипуляторов после выборов предать огласке.

**Comment by frol** [comment]
@imaginal Если бы ты сразу дочитал моё первое предложение то ты бы и точки закрыл... Цитирую конец фразы: "и множественным использованием точек".

**Comment by imaginal** [comment]
@frol Одно дело не пускать email с '+' зная что у пользователя есть версия без '+', другое принудительно нормализовать и хранить отдельно нормализованные и не нормализованные версии email, две таблицы, два индекса, транзакции брр. Система становится неоправданно сложной ;) И все это ради одного GMail — нет лучше я буду следовать rfc 822 и считать это разными адресами.

**Comment by imaginal** [comment]
P.S. доп таблица с нормализованными токенами и таймаутом на их повторное использование (в том числе чтобы нельзя было на один номер часто слать смс расходуя наши средства) задумана но чуток позже, и то если эта голосовалка в принципе еще раз понадобится.
