### ISSUE TITLE
повысить шансы email нотификаций не попадать в спам

### ISSUE THREAD

**Issue by d3m3tr1s** [imaginal/nabuvote#6]
Здравствуйте, увидел пост на фб

https://www.facebook.com/anatoly.chernenko.25/posts/916594458363866

Заранее прошу простить, если не пригодится.

перед строкой https://github.com/imaginal/nabuvote/blob/master/system/functions.php#L296

чтобы не попадать в спам листы желательно добавить

"Return-Path: {$settings['email_from_header']}\r\n" .        

и если позволит аудит, так же

в строке https://github.com/imaginal/nabuvote/blob/master/system/functions.php#L307

изменить на

mail($email, $subject, $message, $headers, "-f {$settings['email_from_header']}");

описано тут 
http://us2.php.net/manual/en/function.mail.php

в параграфе "additional_parameters"

не рабоает если включен safe_mode, хотя в последних версиях этот режим deprecated

**Comment by imaginal** [comment]
Спасибо,
сейчас в email_from_header содержится человеко-читаемый utf-8 отправитель что не позволяет использовать его в Return-Path и тем более в командной строке. Попробую завести для этого  отдельный параметр и проверить на практике, но главная проблема сейчас в том что домен в From и реальный FQDL отправителя не совпадают (я не НАБ) а вот когда это будет на серверах НАБ этот вопрос должен уйти.

**Comment by d3m3tr1s** [comment]
Да, для Return-Path нужно только email@address.com. Некоторые mail провайдеры проверяют этот параметр, т.к. он используется для возвращения оригинального письма, если по какой-то причине, оно не может быть доставленно. Если этот параметр отсуствует - повышаются шансы письма быть квалифицированным как спам.

**Comment by bsgdigital** [comment]
Лучше для транзакционных писем использовать mandrill.com или похожий сервис с простым API - у них delivery rate будет намного выше, чем у собственного сервера. Первые 12 тыс. писем в месяц бесплатно, дальше 20 центов за каждую тысячу.

**Comment by firec0der** [comment]
Практика показывает, что mandrillapp.com отлично работает.

**Comment by imaginal** [comment]
Доставку почты будет обеспечивать админ системы на которой будет работать голосовалка — поэтому отправка почты сделана максимально упрощенной. "Это не бага. Так задумано" (с)
